- hosts: localhost
  gather_facts: False
  tasks:
    - name: Create key pair
      ec2_key:
        name: sample
        region: us-east-1
      register: keyout

        #- name: Print key
        #debug:
        #var: keyout

    - name: Save key
      copy:
        content: "{{keyout.key.private_key}}"
        dest: ./sample.pem
      when: keyout.changed

    - name: start an instance
      amazon.aws.ec2_instance:
        name: "public-compute-instance"
        key_name: "sample"
          #vpc_subnet_id: subnet-5ca1ab1e
        instance_type: t2.micro
        security_group: default
          #network:
          #assign_public_ip: true
        image_id: ami-0230bd60aa48260c6
        region: us-east-1
        exact_count: 1
        tags:
          Environment: Testing
